[package]
name = "RustVoxelEngine"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = { version = "0.34", features = ["macros"] }
vulkano-shaders = "0.34"
winit = { version = "0.30", features = ["rwh_05"]} 
image = "0.25.0"